### ISSUE TITLE
Member finding / replacement library

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#440]
The current ClassMover package was the first part of Phpactor to be written. Since then it has been expanded to find member references, but still the logic for traversing the project tree is in the Phpactor extension, and the whole thing doesn't fit together in a general way (not easy to extend, f.e. to support finding function references).

It would be good to extract a new library (or rename and refactor the existing one) and:

- [ ] Provide a generic symbol replacement API (including f.e. variables, functions, etc).
- [ ] Support project traversal in the library (in addition to single files).
- [ ] Support renaming class files when they are the defining classes.
- [ ] Better handle the namespacing issues (#315, #265)
- [ ] Include support for refactoring namespace? (#275)

**Comment by dantleech** [comment]
Could be implemented via. #464

**Comment by dantleech** [comment]
This would eventually be taken by [reference finder extension](https://github.com/phpactor/reference-finder)
