### ISSUE TITLE
April 2020 release: Language Server Support

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#528]
For the next #918 it would be great to bundle LSP support. There has been some significant progress.

Features (from [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_rename)):

- [x] Completion
- [x] Signature help
- [x] Goto Definition
- [x] Hover
- [x] Goto Type
- [ ] Code Lens (not sure if WR will return the documentation prose)
- [ ] Goto declaration (:warning: this is new functionality, but is possible with the WR Frame)
- [ ] References (:warning: long blocking)
- [ ] Implementations
- [ ] Rename (:warning: long blocking)
- ???

Indexing:

- [ ] [Indexer](https://github.com/phpactor/indexer): (#912) Provides a background indexing process on the server to support goto implementation(s) and classes / functions not tracked by composer.

Improvements:

- [x] Language Server services should be started on `initialized` instead of `initialize`
- [ ] Support progress notifications #912 
- [x] <strike>Combine extensions into packages, e.g. `phpactor/reference-finder` can also bundle the LSP extensions.</strike> will not do, see ADR.
- [x] Bundle Language Server by default

Other:

- [x] Performance / blocking (e.g. in class such as "product writer step")
- [x] Occasionally only methods completions are shown???
- [ ] Server idles at around 10% CPU
- [x] Implement `cancelRequest` (or at least a stub for it)
- [x] implement "shutdown"
- [x] Completion too slow (classes) start at 3 chars?
- [x] Worse Reflection cache: caching is disabled for the LSP, but this slows down. implement a TTL cache. #929 
- [x] Errors are not shown in CoC - why?
- [ ] Function indexing (currently only classes are indexed)
- [x] Signature helper, active signature out of range, active parameter is null

Nice to have:

- [ ] Refactor Language Server to use co-routines (return Proimises instead of Generators from handlers): this will also help prevent blocking with f.e.. completion.

## Code Lens and Signature Help Example (intelliphense)

![Untitled](https://user-images.githubusercontent.com/530801/77919170-c1c71f00-7294-11ea-8652-f51b3ab550db.png)

**Comment by seagoj** [comment]
I'd be interested in this. Particularly the ALE integration.

**Comment by dantleech** [comment]
This is currently naively implemented by the [language server extension](https://github.com/phpactor/language-server-extension) (both over STDIN and TCP) but it can crash with prolonged use and it can only process one request at a time. Rewriting / refactoring it to process multiple requests would be the next step.

**Comment by dantleech** [comment]
Note further progress has been made, and the above extension has been re-written. Currently supports completion, goto definition and hover (also theoretically signature completion).

There are still some minor quirks and can only work on the `develop` branch.

**Comment by przepompownia** [comment]
> Errors are not shown in CoC - why?

How to reproduce it? I did not found any open issue with an example.

**Comment by dantleech** [comment]
> How to reproduce it?

Error responses (handler not found for unsupported operations) are frequently returned from Phpactor (I've fixed some of the most frequent ones), but there is no indication of them in the client. Perhaps there is a setting in CoC.

**Comment by dantleech** [comment]
Released
